DECLARE chk NUMBER;
BEGIN
 SELECT COUNT(*) INTO chk FROM all_objects WHERE object_type IN ('TABLE','VIEW') AND UPPER(object_name) = UPPER('Account');
 DBMS_OUTPUT.PUT_LINE(chk);
 IF chk <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE Account';
 END IF;
 SELECT COUNT(*) INTO chk FROM all_objects WHERE object_type IN ('TABLE','VIEW') AND UPPER(object_name) = UPPER('Customer');
 DBMS_OUTPUT.PUT_LINE(chk);
 IF chk <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE Customer';
 END IF;
 SELECT COUNT(*) INTO chk FROM all_objects WHERE object_type IN ('TABLE','VIEW') AND UPPER(object_name) = UPPER('Branch');
 DBMS_OUTPUT.PUT_LINE(chk);
 IF chk <> 0 THEN
  EXECUTE IMMEDIATE 'DROP TABLE Branch';
 END IF;
 EXECUTE IMMEDIATE 'CREATE TABLE Branch( B# VARCHAR(3), Address VARCHAR(30) UNIQUE NOT NULL, PRIMARY KEY (B#))';
 EXECUTE IMMEDIATE 'CREATE TABLE Customer( C# VARCHAR(5), Name VARCHAR(10) UNIQUE NOT NULL, PRIMARY KEY (C#))';
 EXECUTE IMMEDIATE 'CREATE TABLE Account( A# VARCHAR(7), C# VARCHAR(5), Balance INTEGER, PRIMARY KEY (A#), FOREIGN KEY (C#) REFERENCES Customer(C#))';
END;
  /
